#!/bin/bash
# Setup implementation plan - initialize plan.md from template

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Parse arguments
JSON_MODE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --json) JSON_MODE=true; shift ;;
        *) shift ;;
    esac
done

# Use check-prerequisites to get paths
PATHS_JSON=$(bash "$SCRIPT_DIR/check-prerequisites.sh" --json --paths-only)

if [ $? -ne 0 ]; then
    echo "Error: Failed to check prerequisites" >&2
    exit 1
fi

# Parse JSON (using grep/sed for simplicity, no jq dependency)
FEATURE_SPEC=$(echo "$PATHS_JSON" | grep -o '"feature_spec": "[^"]*"' | sed 's/"feature_spec": "\(.*\)"/\1/')
IMPL_PLAN=$(echo "$PATHS_JSON" | grep -o '"impl_plan": "[^"]*"' | sed 's/"impl_plan": "\(.*\)"/\1/')
SPECS_DIR=$(echo "$PATHS_JSON" | grep -o '"specs_dir": "[^"]*"' | sed 's/"specs_dir": "\(.*\)"/\1/')
BRANCH=$(echo "$PATHS_JSON" | grep -o '"branch": "[^"]*"' | sed 's/"branch": "\(.*\)"/\1/')

# Verify spec exists
if [ ! -f "$FEATURE_SPEC" ]; then
    echo "Error: Feature spec not found at $FEATURE_SPEC" >&2
    exit 1
fi

# Create plan.md from template if it doesn't exist
if [ ! -f "$IMPL_PLAN" ]; then
    TEMPLATE="$REPO_ROOT/.specify/templates/plan-template.md"

    if [ -f "$TEMPLATE" ]; then
        cp "$TEMPLATE" "$IMPL_PLAN"
        echo "Created plan.md from template" >&2
    else
        # Create minimal plan.md if template doesn't exist
        cat > "$IMPL_PLAN" <<'EOF'
# Implementation Plan

**Feature ID:** TBD
**Status:** Planning
**Version:** TBD

---

## Overview

[Plan content will be generated by /specify:plan command]

---

## Phases

### Phase 0: Research

TBD

### Phase 1: Implementation

TBD

### Phase 2: Testing

TBD

---

## Success Criteria

TBD
EOF
        echo "Created minimal plan.md" >&2
    fi
fi

# Output paths
if [ "$JSON_MODE" = true ]; then
    cat <<EOF
{
  "branch": "$BRANCH",
  "feature_spec": "$FEATURE_SPEC",
  "impl_plan": "$IMPL_PLAN",
  "specs_dir": "$SPECS_DIR"
}
EOF
else
    echo "FEATURE_SPEC=$FEATURE_SPEC"
    echo "IMPL_PLAN=$IMPL_PLAN"
    echo "SPECS_DIR=$SPECS_DIR"
    echo "BRANCH=$BRANCH"
fi

exit 0
